[project]
name = "rag-knowledge-base-exploration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sivahere4cloud", email = "sivaganeshcloud@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "openai>=3.19.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
rag-knowledge-base-exploration = "rag_knowledge_base_exploration:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
